export const GAME_CONFIG = {
  WORLD_WIDTH: 5000,
  WORLD_HEIGHT: 5000,
  TILE_SIZE: 64,
  PLAYER_SPEED: 200,
  SHIP_SPEED: 150,
  TURN_SPEED: 2,
  DASH_SPEED: 800,
  DASH_DURATION: 150,
  DASH_COOLDOWN: 400,
  ATTACK_RANGE: 60,
  ATTACK_DAMAGE: 20,
  ATTACK_COOLDOWN: 300,
  PROJECTILE_SPEED: 500,
  PROJECTILE_DAMAGE: 15,
  MAX_STAMINA: 100,
  STAMINA_REGEN: 20,
  DASH_STAMINA_COST: 25,
  ATTACK_STAMINA_COST: 15
};

export const EVENTS = {
  PLAYER_JOIN: 'player:join',
  PLAYER_LEAVE: 'player:leave',
  PLAYER_MOVE: 'player:move',
  PLAYER_UPDATE: 'player:update',
  PLAYER_DASH: 'player:dash',
  PLAYER_ATTACK: 'player:attack',
  SHIP_UPDATE: 'ship:update',
  WORLD_STATE: 'world:state',
  PROJECTILE_FIRE: 'projectile:fire',
  HIT: 'hit',
  DAMAGE: 'damage'
};